org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true

kotlin.code.style=official

# Termux/Android aarch64: el aapt2 de AGP es x86-64 y no puede ejecutarse aqui.
# Se usa un aapt2 nativo compilado con el NDK.
android.aapt2FromMavenOverride=/data/data/com.termux/files/home/buildtools/aapt2-native/aapt2
